import type { Category, Person, Settings, Subscription } from "./types";

const n3: Subscription["notify"] = [
  { daysBefore: 30, enabled: true },
  { daysBefore: 3, enabled: true },
  { daysBefore: 0, enabled: false },
];

function st(created: string, updated: string, notes = ""): Pick<Subscription, "createdAt" | "updatedAt" | "notes"> {
  return { createdAt: created, updatedAt: updated, notes };
}

/** Static demo: varied cycles so the last-6-months chart and breakdowns are not flat. */
export const DEMO_PEOPLE: Person[] = [
  { id: "me", name: "Yo", color: "#ffaa1f", emoji: "🙂" },
  { id: "ana", name: "Ana", color: "#ec4899", emoji: "✨" },
  { id: "lucas", name: "Lucas", color: "#3b82f6", emoji: "🎸" },
];

export const DEMO_CATEGORIES: Category[] = [
  { id: "entertainment", name: "Entretenimiento", color: "#7c5cff", emoji: "🎬" },
  { id: "productivity", name: "Productividad", color: "#2dd4bf", emoji: "💼" },
  { id: "lifestyle", name: "Estilo de vida", color: "#f59e0b", emoji: "🌴" },
  { id: "utilities", name: "Servicios", color: "#60a5fa", emoji: "🔌" },
  { id: "education", name: "Cursos", color: "#a855f7", emoji: "📚" },
];

export const DEMO_SUBSCRIPTIONS: Subscription[] = [
  {
    id: "demo_netflix",
    name: "Netflix",
    domain: "netflix.com",
    price: 3200,
    currency: "ARS",
    cycle: "monthly",
    startDate: "2023-01-08",
    endDate: null,
    totalPayments: null,
    active: true,
    personId: "me",
    categoryId: "entertainment",
    raises: [
      { id: "n1", date: "2025-10-01", newPrice: 3600, note: "Plan estándar" },
    ],
    notify: n3,
    ...st("2023-01-08T10:00:00.000Z", "2025-10-01T10:00:00.000Z"),
  },
  {
    id: "demo_spotify",
    name: "Spotify",
    domain: "spotify.com",
    price: 399,
    currency: "ARS",
    cycle: "monthly",
    startDate: "2022-11-10",
    endDate: null,
    totalPayments: null,
    active: true,
    personId: "me",
    categoryId: "entertainment",
    raises: [],
    notify: n3,
    ...st("2022-11-10T10:00:00.000Z", "2022-11-10T10:00:00.000Z"),
  },
  {
    id: "demo_notion",
    name: "Notion",
    domain: "notion.so",
    price: 12,
    currency: "USD",
    cycle: "monthly",
    startDate: "2023-04-20",
    endDate: null,
    totalPayments: null,
    active: true,
    personId: "ana",
    categoryId: "productivity",
    raises: [],
    notify: n3,
    ...st("2023-04-20T08:00:00.000Z", "2023-04-20T08:00:00.000Z"),
  },
  {
    id: "demo_icloud",
    name: "iCloud",
    domain: "icloud.com",
    price: 2.99,
    currency: "USD",
    cycle: "monthly",
    startDate: "2020-01-03",
    endDate: null,
    totalPayments: null,
    active: true,
    personId: "me",
    categoryId: "utilities",
    raises: [],
    notify: [
      { daysBefore: 0, enabled: true },
      { daysBefore: 0, enabled: false },
      { daysBefore: 0, enabled: false },
    ],
    ...st("2020-01-03T10:00:00.000Z", "2020-01-03T10:00:00.000Z"),
  },
  {
    id: "demo_adobe",
    name: "Adobe",
    domain: "adobe.com",
    price: 14999,
    currency: "ARS",
    cycle: "quarterly",
    startDate: "2025-02-10",
    endDate: null,
    totalPayments: null,
    active: true,
    personId: "lucas",
    categoryId: "productivity",
    raises: [],
    notify: n3,
    ...st("2025-02-10T10:00:00.000Z", "2025-02-10T10:00:00.000Z"),
  },
  {
    id: "demo_vercel",
    name: "Vercel",
    domain: "vercel.com",
    price: 2400,
    currency: "ARS",
    cycle: "yearly",
    startDate: "2022-11-20",
    endDate: null,
    totalPayments: null,
    active: true,
    personId: "me",
    categoryId: "utilities",
    raises: [],
    notify: n3,
    ...st("2022-11-20T10:00:00.000Z", "2022-11-20T10:00:00.000Z"),
  },
  {
    id: "demo_domain",
    name: "Dominio .com",
    emoji: "🌐",
    color: "#94a3b8",
    price: 18000,
    currency: "ARS",
    cycle: "yearly",
    startDate: "2018-04-12",
    endDate: null,
    totalPayments: null,
    active: true,
    personId: "me",
    categoryId: "utilities",
    raises: [],
    notify: [
      { daysBefore: 7, enabled: true },
      { daysBefore: 0, enabled: false },
      { daysBefore: 0, enabled: false },
    ],
    ...st("2018-04-12T10:00:00.000Z", "2018-04-12T10:00:00.000Z", "Renovación anual"),
  },
  {
    id: "demo_onetime_december",
    name: "Regalo Kindle",
    domain: "amazon.com",
    price: 14.5,
    currency: "USD",
    cycle: "onetime",
    startDate: "2025-12-01",
    endDate: null,
    totalPayments: 1,
    active: true,
    personId: "ana",
    categoryId: "lifestyle",
    raises: [],
    notify: [
      { daysBefore: 0, enabled: false },
      { daysBefore: 0, enabled: false },
      { daysBefore: 0, enabled: false },
    ],
    ...st("2025-12-01T12:00:00.000Z", "2025-12-01T12:00:00.000Z", "Ebook (un pago)"),
  },
  {
    id: "demo_onetime_feb",
    name: "Curso Domestika",
    domain: "domestika.org",
    price: 18,
    currency: "USD",
    cycle: "onetime",
    startDate: "2026-02-05",
    endDate: null,
    totalPayments: 1,
    active: true,
    personId: "me",
    categoryId: "education",
    raises: [],
    notify: [
      { daysBefore: 0, enabled: false },
      { daysBefore: 0, enabled: false },
      { daysBefore: 0, enabled: false },
    ],
    ...st("2026-02-05T10:00:00.000Z", "2026-02-05T10:00:00.000Z", "Ilustración — pago único"),
  },
  {
    id: "demo_onetime_march",
    name: "Taller presencial",
    emoji: "🎟️",
    color: "#f43f5e",
    price: 55000,
    currency: "ARS",
    cycle: "onetime",
    startDate: "2026-03-15",
    endDate: null,
    totalPayments: 1,
    active: true,
    personId: "lucas",
    categoryId: "education",
    raises: [],
    notify: [
      { daysBefore: 0, enabled: false },
      { daysBefore: 0, enabled: false },
      { daysBefore: 0, enabled: false },
    ],
    ...st("2026-03-15T10:00:00.000Z", "2026-03-15T10:00:00.000Z", "Workshop (un pago)"),
  },
  {
    id: "demo_chatgpt",
    name: "ChatGPT Plus",
    domain: "openai.com",
    price: 20,
    currency: "USD",
    cycle: "monthly",
    startDate: "2024-07-11",
    endDate: null,
    totalPayments: null,
    active: true,
    personId: "lucas",
    categoryId: "productivity",
    raises: [],
    notify: n3,
    ...st("2024-07-11T10:00:00.000Z", "2024-07-11T10:00:00.000Z"),
  },
];

export const DEMO_SETTINGS: Settings = {
  id: "singleton",
  language: "es",
  accentPreset: "amber",
  useCompactAmounts: true,
  primaryCurrency: "ARS",
  notificationsEnabled: false,
  fx: {
    base: "ARS",
    rates: {
      ARS: 1,
      USD: 0.00068,
      EUR: 0.00063,
    },
    fetchedAt: "2024-12-20T00:00:00.000Z",
  },
};
